### ISSUE TITLE
Validate value consistency based on property values

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#223]
To improve advanced validation, it should be possible to define and validate a rule that test value consistency, i.e. performs checks of the type `"If property X has value A, then property Y must have value B"` or `"If property X has value A, then property Y must have one of the following values: A, B, C, or D"`. 

As with issue #222 , I see two ways of implementing this:

1. Adding a schematron validator
1. Extending the internal validator (which would also require UI elements to define the additional contraints)

If the second approach is selected, I'd propose to use the Properties view and add a new tab for "Additional Constraints" where those may be defined. We could re-use the i3s validator approach.

**Comment by arunverma87** [comment]
For example,
One can write schematron rules as below,
case 1: `"If property X has value A, then property Y must have value B"`

`<sch:assert test = "(mudab:parameterCode!='CD') or (mudab:parameterCode='CD' and mudab:unit='ug/kg')"> if parameterCode has value 'CD' then unit should be 'ug/kg', otherwise omit the rule</sch:assert>`

case 2: `"If property X has value A, then property Y must have one of the following values: A, B, C, or D"`

`<sch:assert test = "(mudab:parameterCode!='FATWT') or (mudab:parameterCode='FATWT' and (mudab:unit='ug/kg' or mudab:unit='ug/kg1' or mudab:unit='ug/kg2'))"> if parameterCode has value 'FATWT' then unit must one of  'ug/kg' or 'ug/kg1' or 'ug/kg2', otherwise omit the rule</sch:assert>`
