### ISSUE TITLE
Schema/Alignment Migration Wizard Enhancements

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#397]
The schema migration process, respectively the process to adopt an alignment to a new schema, currently can require a lot of redundant user inputs, and can also otherwise be improved:

- [x]  Cancel process: It is as of now not possible to cancel the entire process, which means a user has to click many many times. ~~Cancel should end the whole process, basically undoing any assignments that have already been made.~~
- [x]  Remember previously made assignments: If I've already mapped a type entity from the previous schema to the new one, all following type ~~and property~~ assignments should remember that. If I've already mapped a property entity from the previous schema to the new one, the wizard should also remember that.
- [ ] ~~Adjust scripts: If an entity is replaced in a Groovy function, the name of that entity should also be replaced in the script.~~

**Comment by florianesser** [comment]
Cancelling is possible in [this build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/344/). The current implementation does not undo assignments made before Cancel was pressed, though.

**Comment by stempler** [comment]
@florianesser implemented that pressing *Cancel* will abort the process.
Some comments related to that and the original issue description:

> Cancel should end the whole process, basically undoing any assignments that have already been made.

This contradicts the instructions that are still provided to the user, where it is explained what Cancel does (did). So I would suggest either adding a *Cancel all* button or changing the instructions.

I don't think changes a user did up to the point where he/she pressed Cancel should be undone (and I also don't see an easy way to do that).


I vote for dividing this issue. Especially because of this task:

> Adjust scripts: If an entity is replaced in a Groovy function, the name of that entity should also be replaced in the script.

To have something reliable in place here is much effort, and something we did not attempt for any migration projects so far. I suggest to reevaluate this in respect to the recent changes done to the migration, if maybe having required manual changes documented as tasks is enough or what would be the most efficient ways to work towards such a functionality.

**Comment by stempler** [comment]
With https://github.com/halestudio/hale/pull/565 the dialog will not ask more than once for the same entity. It will also look for a candidate for properties in a previously associated type, but a property candidate is currently only identified based on equal local names.

**Comment by stempler** [comment]
@thorsten-reitz The functionality described in the in the first two tasks is implemented partially:

1. The resolving process can be canceled, but there is no *undoing* of *any assignments that have already been made*.
2. Previously made assignments are remembered, but an assigned type only results in a suggestion for a property if a property with the same name can be found in the type

My suggestion to continue with this issue would be the following:

1. Create a separate issue for task 3 (though I would not see that)
2. If you think the "undoing" is important, create an enhancement ticket for task 1 (the basic idea is then to instead of doing the replacement during loading the alignment, to do it afterwards and replace the cells, which can be done as "all or nothing" and can even be undone)
3. If you have concrete idea how to improve the current behavior regarding task 2, create an enhancement ticket
4. Close this ticket (all new tickets will not be part of this milestone)

**Comment by thorsten-reitz** [comment]
@stempler The idea with the UNDO was that because in the past, if I made a single error I would have to either redo the entire process or remember the change to be made and then later make it on the alignment. 

For Task 2, the expectation was that if I make a certain assignment of a type or property in a type from the cell to be migrated to a new schema, and later I have another cell that has the same "old" source property/type, it is remembered and proposed (so that I can confirm it).

With respect to Task 3, can we generate a task instead so that I have a reminder that I need to change the Groovy Script later on?

**Comment by thorsten-reitz** [comment]
LGTM
