### ISSUE TITLE
More robust code list and schema loading from local resources

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#420]
After the temporary JRC switch from HTTP to HTTPS on July 19th, some issues became apparent in the loading of resources in hale. Within this ticket, these should be documented and fixed.

**Comment by florianesser** [comment]
When the INSPIRE schemas were unavailable, hale studio was unable to load the schemas although they are available in the local resources. This was due to the fact that local resources were only used for resolving references schemas but not for loading the top-level schemas of an alignment. This has been fixed in #415.

**Comment by florianesser** [comment]
After the INSPIRE schemas were moved from `http` to `https` URLs, references to the old `http` URLs could no longer be resolved in headless mode, althoiugh a redirect to the `https` URL was in place. The redirect was not followed by hale, because the `Request` class failed to initialize in headless mode and the fallback `URL.openStream()` does not follow redirects but simply fetches the empty body of the HTTP 302 (Redirect). To overcome this, the `Request` class was fixed in #413 to also work in headless mode.

**Comment by florianesser** [comment]
[Build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/282/) containing #412, #413 and #415.
