### ISSUE TITLE
Save shared project remotely

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#422]
When the user saves a project that has been shared, the project should also be updated remotely on any save.

I would propose to add an option to the "Share project..." wizard to always update the remote project when saving. This option should by default be activated. When going through the "Share project" wizard again, the setting can be changed.

Furthermore, when using "Sale Alignment Project as..." to save to a local file again, saving should afterwards update only the local copy. This makes it more transparent when the project is saved where. In this way, a user can revert to an offline workflow when they are not able to connect or want to do some work on their local machine only.

**Comment by florianesser** [comment]
This is related to #372 and #375. The `ProjectWriter` needs to handle cases properly where the project location is not a file (see #411).

**Comment by florianesser** [comment]
In its current state, the implementation supports saving changes directly back to hale connect only for projects that were previously imported from there. Therefore, after uploading a project with the "Share project" wizard the user must first open the uploaded project from hale connect before being able to save changes remotely via the "Save" operation. Although this requires an extra step, I think this is consistent with hale's save/export philosophy.

@tr Adding the wizard option you suggested would require more work. Do you think the current implementation would suffice?

**Comment by thorsten-reitz** [comment]
@florianesser Would the workflow to first create a project, the share it/save it on haleconnect, and then all updates are saved on haleconnect too work already? Is is possible to switch via "Save as" to using a local file again?

**Comment by florianesser** [comment]
Saving to hale connect immediately after sharing is not yet possible. Before being able to save updates to hale connect you would have to load it from there first (step 3):

1. Create project (or load from local file)
2. Share project to hale connect _[this is an export, pressing "Save" immediately afterwards would trigger "Save as" if the project is new or otherwise save to the project back to the local file]_
3. Load the project from hale connect
4. Change project and...
4.1 "Save" _[this will save directly to hale connect]_
4.2 "Save as" _[save to a local file, switch to "offline" workflow]_

Allowing to save updates immediately after sharing would require supporting a true "Save as" for the non-file target hale connect.

**Comment by florianesser** [comment]
@thorsten-reitz The workflow that you suggested is now implemented.

**Comment by thorsten-reitz** [comment]
@florianesser thanks, will test as soon as the build is available.

**Comment by florianesser** [comment]
Can be tested together w/ #429 (link to feature build there)
