### ISSUE TITLE
Develop concept for UI supported merge workflow

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#474]
Concept for performing the merge workflow in the hale studio UI. This should include handling of uncertainties (see https://github.com/halestudio/hale-cli/issues/41).

**Comment by thorsten-reitz** [comment]
Should I work on that?

**Comment by florianesser** [comment]
@stempler @thorsten-reitz I suggest the following to add basic support for managing messages created by the alignment merger process:
- Add a view to hale studio that lists all messages in the alignment (based on the relatively simple Eclipse "Tasks" view layout)
- Allow navigating directly to the respective cell of the task entry
- Allow marking tasks as "finished"/"dismissed" directly in the list

![2018_02_05_12_24_06_hale_studio_tasksview](https://user-images.githubusercontent.com/1867607/35802883-1b62b2fa-0a72-11e8-9898-73eada23c421.png)

When a task is dismissed, this will be persisted in the alignment file via the `dismissed` property of the `Message` class. Ideally, this will then be part of the diff created by the Gradle migration so that the task will remain dismissed when rerunning the migration.

This basic support could be improved upon in the future:
- Add transformation warning/error markers
- Migrate to a Mylyn-based workflow with support for local tasks and task repositories (e.g. hale connect)

**Comment by thorsten-reitz** [comment]
@florianesser thanks for the proposal. I would just like to understand the workflow a bit better - so would it be like this?

1. User loads an alignment, hale parses it and looks for messages, and then creates an entry in the task view for each message found
1. User clicks on a task, hale displays the cell in the Alignment or Mapping view
1. If the task merely requires to check the correctness of the cell, the user can "Dismiss" the task
1. If it requires editing, User edits cell though cell wizard
1. After editing and transformation, user sets state of task to "finished" (or, even better, when no trafo errors are introduced, the user is prompted whether they want to set the task to finished)

The second question would be if we would also have an option to create the merged alignment through the UI. That could IMHO be a simple dialog added to File -> Merge Alignment Projects... which allows to select two alignments. @stempler should the wizard check that the "B" schema is the same in the first and second project?

**Comment by florianesser** [comment]
@thorsten-reitz That's exactly the workflow I had in mind for the minimal implementation.

**Comment by thorsten-reitz** [comment]
@florianesser OK thanks, just wanted to make sure there wasn't too many assumptions that would later run wild :).

**Comment by florianesser** [comment]
My initial idea of reusing Eclipse's `Tasks` view (or even doing an integration of Mylyn) appears unfeasible after all because of tight coupling with the `org.eclipse.ui.ide` bundle which would introduce unwanted UI contributions (and lot of new dependencies) to hale.

The discussions in the Eclipse community about uncoupling this seem to have stalled a long time ago:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=227639
https://bugs.eclipse.org/bugs/show_bug.cgi?id=283877
https://bugs.eclipse.org/bugs/show_bug.cgi?id=246150
