### ISSUE TITLE
Support AdV CRS codes

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#524]
Support (some) AdV CRS codes by translating them to EPSG codes.
A nice addition would also being able to read default CRS information from an "NBA Bestandsdatenauszug".

**Comment by florianesser** [comment]
@stempler I did a quick spike [here](https://github.com/florianesser/hale/tree/feature/adv-crs-codes) implementing a `CRSAuthorityFactory` for the AdV codes. Would that be a viable route to follow in your opinion?

**Comment by florianesser** [comment]
> Would we then also be able to output the srsName w/ the AdV codes?

Not trivially. The AdV codes are mapped internally to EPSG codes and the `CoordinateReferenceSystem` objects returned by the new factory only contain the EPSG code. Therefore, after the initial lookup, they behave as if the EPSG code had been read instead of the AdV code.

If we want to also support writing these codes, we would also have to make changes [here](https://github.com/halestudio/hale/blob/ce78a4da5c90b18b3ceb70ebfe0cb5033a3d3caf/common/plugins/eu.esdihumboldt.hale.common.instance/src/eu/esdihumboldt/hale/common/instance/io/impl/AbstractGeoInstanceWriter.java#L286) for example. I would suggest to handle this in an enhancement ticket where we could consider to generalize the CRS support towards supporting multiple authorities (like AdV and possibly ISO in the future).

**Comment by stempler** [comment]
> Not trivially. The AdV codes are mapped internally to EPSG codes and the CoordinateReferenceSystem objects returned by the new factory only contain the EPSG code. Therefore, after the initial lookup, they behave as if the EPSG code had been read instead of the AdV code.

If the `CodeDefinition` uses the AdV code when writing the output it could well use that code. Let's see how it behaves when testing.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/373/)

**Comment by florianesser** [comment]
> If the CodeDefinition uses the AdV code when writing the output it could well use that code. Let's see how it behaves when testing.

Works indeed, here's a sample output when I configured the GML writer to transform to `urn:adv:crs:etrs89_lat-lon`:
```
<gml:Polygon gml:id="_c408bd00-eecc-46d2-b48c-4b195f36a0a4" srsName="urn:adv:crs:etrs89_lat-lon" srsDimension="2">
```

**Comment by stempler** [comment]
I successfully tested
- transforming a data set with hale-cli, leaving the CRS untouched (AdV codes were present in the transformed data)
- transforming a data set with hale-cli, transforming the CRS
- loading data w/ hale studio
