### ISSUE TITLE
Partition GML output by FeatureType

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#564]
In cases where different feature types will be published as or processed as individual data sets, it would be helpful to be able to partition the writing of GML objects by feature type. This should be an option that is available in addition to the existing partitioning schemes, so that I can combine e.g. writing a maximum of 1.000 objects of a file.

The filename should also include the feature type name.

**Comment by florianesser** [comment]
How would we handle references between features types in these cases? I think we would only be able to produce output that will not pass XML validation, similar to the `cut` partitioning mode.

**Comment by florianesser** [comment]
The same question applies to #453, btw. Any kind of output partitioning scheme that does not take inter-feature relations into account will suffer from the problem of broken references (e.g. a GML file may not validate b/c a referenced features was written to another file). Would this be something that we leave for the user to solve (e.g. by post-processing the result w/ other tools)?

**Comment by florianesser** [comment]
@thorsten-reitz After discussing this w/ Simon, we have come to the conclusion that adding a scheme to partition by feature type would be relatively straight-forward, given that we don't allow the combination w/ other partitioning schemes. We therefore suggest to limit the scope of this ticket accordingly for this milestone.

The reason is that handling the inter-file references becomes easier when all features of that type will be in the same file. Otherwise some kind of pre- or post-postprocessing with indexing would have to be performed to know which feature ended up in which file.

**Comment by thorsten-reitz** [comment]
@florianesser OK so it would simply be an alternative to partioning by feature count for the moment.

**Comment by florianesser** [comment]
Exactly.

**Comment by florianesser** [comment]
[Feature build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/384/)
