### ISSUE TITLE
Integrate new default base map

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#64]
The MapQuest map used as a base map in hale until now [is no longer available](http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/). Thus we need to look for an alternative. Preferred would be a map that also uses a simple URL pattern for accessing tiles based on zoom level and x/y ordinates.

Any suggestions are welcome.

**Comment by thorsten-reitz** [comment]
Well, there is...

1. [Google Maps](https://developers.google.com/maps/documentation/javascript/examples/maptype-image)
1. [Bing Maps](https://msdn.microsoft.com/en-us/library/bb259689.aspx)
1. [ArcGIS Online Maps](http://www.arcgis.com/home/group.html?owner=esri&title=Tiled%20Basemaps) , which has lots of different basemaps
1. [OSM Tiles](tile.openstreetmap.org)

All of these use the same tiling scheme. All of them are free to access, though with caveats in each case. Some, like OSM, [impose technical limits](http://wiki.openstreetmap.org/wiki/Tile_usage_policy) and require as to get approval first.

I think we should use this opportunity to make the basemap a preference setting, so that it would also be possible to use e.g. any custom WMTS in addition to preconfigured services like those above.

**Comment by thorsten-reitz** [comment]
We've used OSM in the past, and have regularly hit their usage limits. After soliciting feedback from Esri, I learned that...:

(a) Allowing hale users to use any of their own content on ArcGIS Online:

Creating a 3rd party application that requires an ArcGIS Online login is permitted. As the developer, you will want to register for an ArcGIS Online Developer account.

(b) using ArcGIS online basemaps for all users:

Creating an app for anonymous users is permitted through ArcGIS Online for Developers where you register the app and include your AppID which designates you as the developer (and holds you responsible for any credits consumed, if the app permits). In this case, you could leave a placeholder in the open source for the AppID for the developer to insert their own.

Here are a couple of FAQ’s relative to your questions. You can find them all here: https://developers.arcgis.com/terms/faq/

 _What can I do with the free development and testing plan?_  

…You can also use this plan to build apps for public, non-revenue generating, non-government, non-commercial use…

…If you are using 3rd Party development tools, you must include attribution acknowledging that your app is using online services provided by Esri.

**Comment by stempler** [comment]
New default base map is [Stamen Terrain](http://maps.stamen.com/terrain/#3/42.62/15.29).
Users can configure custom maps based on a Web Map Service or a tile URL pattern (zoom/x/y tile coordinates, Pseudo Mercator projection).

**Comment by stempler** [comment]
Added [wiki page on map configuration](https://github.com/halestudio/hale/wiki/Map-configuration).

**Comment by stempler** [comment]
As a new default base map is present, anything else should go into a dedicated issue.
