### ISSUE TITLE
GetCapabilities URL does not work in 3.4.1, but works in 3.5.0

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [halestudio/hale#708]
This RWS GetCapabilities URL works in hale studio 3.5.0, but not in 3.4.1:
http://geoservices.rijkswaterstaat.nl/apps/geoserver/verkeersscheidingsstelsel_nz/ows?service=WFS&request=getcapabilities

I am trying to generate a DescribeFeature request.

**Comment by florianesser** [comment]
What's the error message?

**Comment by Kate-Lyndegaard** [comment]
![grafik](https://user-images.githubusercontent.com/36956461/48551608-4a2e6500-e8d6-11e8-9144-91fb4692a1a7.png)

**Comment by florianesser** [comment]
That URL doesn't work for me in 3.4.1 nor in 3.5.0. The `Could not parse XML document` error occurs because the `http` URL redirects to the corresponding `https` URL. 

If you try the `https` URL instead, you need to make sure that you have the `Staat der Nederlanden Root CA - G3` certificate in your `jre/lib/security/cacerts`.

I'll close this issue in favor of the more general #712.
