### ISSUE TITLE
Follow HTTP 301/302 redirects when opening URLs

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#712]
With the widespread deployment of SSL certificates, plain `http` connections get redirected to `https` more and more often. The method
```
URL url = new URL("http://www.example.org");
InputStream is = url.openStream();
```
will return an empty `InputStream` if e.g. `http://www.example.org` redirects to `https://www.example.org`.

An approach to follow redirects might be to something like
```
HttpURLConnection c = (HttpURLConnection) url.openConnection();
Set<String> visitedUrls = new HashSet<>();
boolean doneRedirecting = false;
while (!doneRedirecting) {
	switch (c.getResponseCode()) {
	case HttpURLConnection.HTTP_MOVED_PERM:
	case HttpURLConnection.HTTP_MOVED_TEMP:
		// Follow redirect if not already visisted
		String newLocation = c.getHeaderField("Location");
		if (visitedUrls.contains(newLocation)) {
			throw new RuntimeException(MessageFormat.format(
				"Infinite redirect loop detected for URL {0}", usedUrl.toString()));
		}
		visitedUrls.add(newLocation);

		url = new URL(newLocation);
		c = (HttpURLConnection) url.openConnection();
		break;
	default:
		doneRedirecting = true;
		break;
	}
}

try (InputStream is = c.getInputStream()) {
	// something
}
```

**Comment by JohannaOtt** [comment]
There are also redirects implemented for the INSPIRE schemas which leads to the fact that the XML validation fails when exporting data using an http URI (e.g. http://inspire.ec.europa.eu/schemas/hh/4.0/HumanHealth.xsd)

**Comment by JohannaOtt** [comment]
Another case where redirects cause issues is the apiso metadata schema http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd. When trying to import it to hale studio the error message `java.lang.RuntimeException: org.apache.ws.commons.schema.XmlSchemaException: Referenz zu Entity "l" muss mit dem Begrenzungszeichen ";" enden.` is returned.
This is due to the fact that the schema http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd is loaded recursively. This schema is redirected to its https variant which causes the error.

**Comment by florianesser** [comment]
Given that virtually all resources are behind https URLs these days, I don't think this is relevant anymore.
