### ISSUE TITLE
hale studio 4.0.0 does not install on Windows 10

### ISSUE THREAD

**Issue by jbroq** [halestudio/hale#880]
Hi,

The following MSI is not allowed to install on windows 10 "Microsoft Defender SmartScreen"
https://github.com/halestudio/hale/releases/download/4.0.0/hale-studio-4.0.0-en-x64.msi

As I am using a corporation laptop, the case might be high security rights, in any case, I think that security should not be an issue.

Best regards

**Comment by florianesser** [comment]
Hi @jbroq,

Thanks for reaching out. The likely cause for this is that the hale studio installer is not signed and, therefore, considered problematic by Microsoft Defender. To install hale studio with the installer package, you will have to specifically allow installation in Microsoft Defender. This may not be possible due to corporate security constraints.

You could alternatively download the [ZIP archive of hale studio 4.0.0](https://github.com/halestudio/hale/releases/download/4.0.0/hale-studio-4.0.0-win32.win32.x86_64.zip) and unpack it somewhere outside of `C:\Program Files`. You can start hale studio by running `HALE.exe` from the extracted folder.
